### ISSUE TITLE
Provider not supporting darwin_arm64 architechure

### ISSUE THREAD

**Issue by cgriggs01** [SUSE/terraform-provider-susepubliccloud#6]
Hi All,

I was trying to use this to provider but got the following error.

`Provider registry.terraform.io/suse/susepubliccloud v0.0.5 does not have a package available for your current platform, darwin_arm64.`

Do you plan to update an publish a new version of this provider?

**Comment by flavio** [comment]
I've done some cleanup and enabled this target. There's a v0.0.6-rc1 that is currently building. I'll ping you here once it's ready to be tested

**Comment by flavio** [comment]
You can find all the binaries over there: https://github.com/SUSE/terraform-provider-susepubliccloud/releases/tag/v0.0.6-rc1

Please, let me know if everything works fine.

**Comment by cgriggs01** [comment]
Thanks you @flavio ! 

Closing issue now.
